name: Artillery Action to test endpoint function users-userId-tasks-taskId

on:
  push:
    branches:
      - development # On merge with master, call this action

env:
  NODE_VERSION: '14'  # the version of node we are using
  NPM_CONFIG_PREFIX: "~/.npm-global" # Required to set path for artillery call
  # STAGE_NAME: merge-perf-test
  # FILE: artillery_${{ steps.date.outputs.date }}.json
  # FILE: test.txt
  # AWS_REGION: 'us-west-2'
  # S3_BUCKET: artillery # TODO: Change once s3 secret is created 
  # S3_KEY:
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  setup:
    runs-on: ubuntu-latest # tells GH actions what we'll be running everything on

    steps:
    - name: 'Checkout Repository GitHub Action' # checks out the repository
      uses: actions/checkout@v2

    - name: 'create blank'
      run: |
        mkdir test
        cd test
        touch test.txt

    # - name: Setup Node ${{ env.NODE_VERSION }} Environment # this is the script that sets up node
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}
    #     check-latest: true
    
    # - name: 'Run npm init'
    #   run: npm init -y

    # - name: Run npm install artillery  
    #   run: npm install -g artillery

    # # - name: Check global npm location
    # #   run: npm list -g

    # - name: Get current date
    #   id: date
    #   run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    # - name: Sleep
    #   run: sleep 10s

    # # Path set by github actions.
    # - name: Run Artillery Test
    #   run: /home/runner/.npm-global/lib/node_modules/artillery/bin/artillery run --output artillery_${{ steps.date.outputs.date }}.json ./test/artillery/artillery-users-user_id-tasks-task_id.yaml

    # - name: Check Artillery Performance test file
    #   run: | 
    #     ls -a
    #     cat artilleryReport_test.json

    # - name: Upload file to bucket # Upload to S3
    #   uses: zdurham/s3-upload-github-action@master
    #   with:
    #     args: --acl public-read

    - name: Upload result to s3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: artillery
        source_dir: 'test'
