name: Artillery Action to test endpoint function users-userId-tasks-taskId

on:
  push:
    branches:
      - development # On merge with master, call this action

env:
  # AZURE_FUNCTIONAPP_NAME: 'nsc-fun-dev-usw2-thursday'
  # AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions'   # relative to the root, where are you keeping the functions
  NODE_VERSION: '14'  # the version of node we are using

jobs:
  setup:
    runs-on: ubuntu-latest # tells GH actions what we'll be running everything on
    steps:
    - name: 'Checkout Repository GitHub Action' # checks out the repository
      uses: actions/checkout@v2

    - name: Setup Node ${{ env.NODE_VERSION }} Environment # this is the script that sets up node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        check-latest: true

    # @@Uncomment for first install to project@@
    - name: 'Run npm init'
      run: npm init -y

    - name: Run npm install artillery  
      run: npm install -g artillery

    - name: go to home
      run: |
        cd /home/runner
        cd /.npm/lib
        cd /node_modules
        ls -a
        

    # @@Uncomment for after first@@
    # - name: 'Resolve Project Dependencies Using Npm' # installs all the packages necessary to run the functions
    #   shell: pwsh
    #   run: |
    #     pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #     npm install
    #     popd

    - name: Sleep
      run: sleep 10s

    - name: Run Artillery Test
      run: /home/runner/.npm/lib/node_modules/artillery/bin/artillery run --output artilleryReport_test.json ./test/artillery/artillery-users-user_id-tasks-task_id.yaml

    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   id: fa
    #   with:
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}